logging:
  level:
    org.springframework: trace
  structured:
    format:
      console: ecs
spring:
  application:
    name: Login Service
authorization-server:
  base-url: http://authorization-server
  redirect-base-uri: http://api-gateway
